export const Rotas = {
	desprotegidas: {
		auth: {
			login: "/login",
			passwordRecovery: "/recuperar-senha",
			register: "/registrar",
		},
		landingPages: {
			home: "/",
			prices: "/precos",
			download: "/download",
			participate: "/participar",
			privacyPolicy: "/politica-de-privacidade",
			knowledgeBase: {
				helpCenter: "/help-center/introducao",
				slug: "/help-center/:slug",
				faq: "/help-center/faq",
			},
		},
		subscription: {
			success: "/subscription/success",
			cancel: "/subscription/cancel",
		},
		designSystem: "/design-system",
		share: "/compartilhar/squad/:token",
		NOT_FOUND: "*",
	},
	protegidas: {
		dashboards: {
			home: "/dashboard",
			overview: "/dashboard/overview",
			reports: "/dashboard/reports",
			records: "/dashboard/records",
			customers: "/dashboard/customers",
			team: "/dashboard/team",
			settings: "/dashboard/settings",
			configuracoes: "/dashboard/configuracoes",
			assinatura: "/dashboard/assinatura",
		},
		admin: {
			overview: "/admin/overview",
			organizations: "/admin/organizations",
			users: "/admin/users",
		},
		orchestrator: {
			squads: "/dashboard/squads",
			squadDetail: "/dashboard/squads/:id",
			scripts: "/dashboard/scripts",
			models: "/dashboard/modelos",
			executions: "/dashboard",
			secrets: "/dashboard/segredos",
			knowledge: "/dashboard/conhecimento",
			knowledgeDetail: "/dashboard/conhecimento/:id",
			assistant: "/dashboard/assistente",
			assistantSession: "/dashboard/assistente/:sessionId",
		},
		legacyOrchestrator: {
			squads: "/orquestrador/squads",
			squadDetail: "/orquestrador/squads/:id",
			scripts: "/orquestrador/scripts",
			models: "/orquestrador/modelos",
			executions: "/orquestrador/execucoes",
			secrets: "/orquestrador/segredos",
			knowledge: "/orquestrador/conhecimento",
			knowledgeDetail: "/orquestrador/conhecimento/:id",
			assistant: "/orquestrador/assistente",
			assistantSession: "/orquestrador/assistente/:sessionId",
		},
	},
};
